### ISSUE TITLE
Create a "Sweep Satscard" UI page

### ISSUE THREAD

**Issue by PeteClubSeven** [PeteClubSeven/breezmobile#4]
Requirements:
- [x] The Bitcoin balance of the public address should be displayed
- [x] The fiat equivalent balance should be displayed
- [x] The fee for sweeping the card should be displayed in Bitcoin and fiat
- [x] Prompt the user to enter the CVC code
- [x] Provide a means of the user inputting the CVC code
- [x] Report incorrect CVC codes to the user
- [x] A button that will attempt to create, sign and broadcast a transaction using the slots private key
    - [x] Open the "Present Satscard" pop up to instruct the user https://github.com/PeteClubSeven/breezmobile/issues/10
    - [x] Unseal the slot, take the private key and construct a transaction: https://github.com/PeteClubSeven/breez/issues/1
    - [x] Report success/failure
    - [x] Open the "Broadcast Transaction" page https://github.com/PeteClubSeven/breezmobile/issues/14
- [x] A button to cancel/close the window
