### ISSUE TITLE
Open the correct UI when a Satscard is detected

### ISSUE THREAD

**Issue by PeteClubSeven** [PeteClubSeven/breezmobile#5]
Requirements:
- [x] When the active slot of the Satscard is unused, open the "Initialize Satscard" UI https://github.com/PeteClubSeven/breezmobile/issues/3
- [x] When the active slot of the Satscard is sealed, open the "Satscard Balance" UI https://github.com/PeteClubSeven/breezmobile/issues/2
- [x] When the Satscard has no active slot open the "Satscard Is Used Up" UI pop up https://github.com/PeteClubSeven/breezmobile/issues/12

**Comment by PeteClubSeven** [comment]
be15fe1edf8253648a1c68e80ed776db26633367

**Comment by PeteClubSeven** [comment]
b65359fe734b9f9005c70c826bef467f04faa483
